[Appearance]
style=Fusion
color_scheme_path=/home/sora/.config/qt6ct/colors/lunar.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default

[Fonts]
general="JetBrains Mono,11"
fixed="JetBrains Mono,11"
