#? Lunar Eclipse — btop (монохром системы)

color_theme = "lunar"
theme_background = True
truecolor = True
force_tty = False
vim_keys = True
rounded_corners = True
terminal_sync = True

update_ms = 1500
clock_format = "%H:%M"

proc_sorting = "cpu lazy"
proc_reversed = False
proc_tree = True
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
proc_cpu_graphs = True
proc_filter_kernel = False
proc_follow_focus = False
proc_left = False

cpu_graph_upper = "Total"
cpu_graph_lower = "Auto"
cpu_invert_lower = True
cpu_single_graph = False
cpu_bottom = False
show_cpu_freq = True

show_uptime = True
check_temp = True
cpu_sensor = "Auto"
show_coretemp = True
temp_scale = "celsius"
show_cpu_watts = True

mem_graphs = True
mem_below_net = False
show_swap = True
swap_disk = True
show_disks = True
only_physical = True
use_fstab = True
zfs_arc_cached = True

net_download = 100
net_upload = 100
net_auto = True
net_sync = False
net_iface = ""

show_battery = True
selected_battery = "Auto"
show_battery_watts = True

show_gpu_info = "Auto"
nvml_measure_pcie_speeds = True

log_level = "WARNING"
suppress_warnings = False
save_config_on_exit = False
